/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}
// Global Components types
declare module 'vue' {
    export interface GlobalComponents {
        Breadcrumbs: typeof import('../src/components/Breadcrumbs/index.vue')['default']
        DictSelect: typeof import('../src/components/DictSelect/index.vue')['default']
        DragResizeble: typeof import('../src/components/DragResizeble/index.vue')['default']
        Settings: typeof import('../src/components/Settings/index.vue')['default']
        Statistic: typeof import('../src/components/Statistic/index.vue')['default']
        Test: typeof import('../src/components/Test/index.vue')['default']
    }
  }
